### ISSUE TITLE
Newer version available

### ISSUE THREAD

**Issue by lighterowl** [parkerlreed/vfs495-files#1]
Hi there, it seems like there was an update of the daemon, which is available from HP here : https://ftp.hp.com/pub/softpaq/sp84501-85000/sp84530.tar . HP occasionally releases updates (this one is supposedly from the 5th of January, though the RPM is dated 29. December) , since it seems like they have a few laptops with Linux officially supported, like this one : https://support.hp.com/us-en/drivers/selfservice/hp-probook-470-g0-notebook-pc/5350448 .

**Comment by parkerlreed** [comment]
I sadly do not have that hardware anymore. I can orphan the PKGBUILD if you want to take it up.

**Comment by lighterowl** [comment]
Gladly. Thanks!

**Comment by parkerlreed** [comment]
Ok it is disowned.

**Comment by parkerlreed** [comment]
That was quick :D
